musicproject/musicapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from rest_framework.urlpatterns import format_suffix_patterns

from models import Library, Artist, Album, Track
from forms import LibraryForm, ArtistForm, AlbumForm, TrackForm
from views import LibraryCreate, LibraryDetail, LibraryList, \
    ArtistDetail, ArtistCreate, ArtistList,\
    AlbumDetail, AlbumCreate, AlbumList,\
    TrackDetail, TrackCreate, TrackList, \
    review, APILibraryReviewDetail, APILibraryReviewList, \
    APILibraryDetail, APIArtistDetail, APIAlbumDetail, APITrackDetail,\
    APILibraryList, APIArtistList, APIAlbumList, APITrackList,\
    LoginRequiredCheckIsOwnerUpdateView

from django.views.generic import RedirectView

urlpatterns = [

    url(r'^librarys(\.(?P<extension>(json|xml)))?$',
        LibraryList.as_view(),
        name='library_list'),

    url(r'^librarys/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        LibraryDetail.as_view(),
        name='library_detail'),

    url(r'^librarys/create/$',
        LibraryCreate.as_view(),
        name='library_create'),

    url(r'^librarys/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Library,
            form_class=LibraryForm),
        name='library_edit'),

    url(r'^librarys/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),

    url(r'^librarys/(?P<pk>\d+)/artists\.(?P<extension>(json|xml))$',
        ArtistList.as_view(),
        name='artist_list'),

    url(r'^librarys/(?P<pk>\d+)/artists/create/$',
        ArtistCreate.as_view(success_url="/musicapp/librarys"),
        name='artist_create'),

    url(r'^librarys/(?P<pkr>\d+)/artists/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        ArtistDetail.as_view(),
        name='artist_detail'),

    url(r'^librarys/(?P<pkr>\d+)/artists/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Artist,
            form_class=ArtistForm),
        name='artist_edit'),

    url(r'^librarys/(?P<pk>\d+)/albums\.(?P<extension>(json|xml))$',
        AlbumList.as_view(),
        name='album_list'),

    url(r'^librarys/(?P<pk>\d+)/albums/create/$',
        AlbumCreate.as_view(success_url="/musicapp/librarys"),
        name='album_create'),

    url(r'^librarys/(?P<pkr>\d+)/albums/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        AlbumDetail.as_view(),
        name='album_detail'),

    url(r'^librarys/(?P<pkr>\d+)/albums/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Album,
            form_class=AlbumForm),
        name='album_edit'),

    url(r'^librarys/(?P<pk>\d+)/tracks\.(?P<extension>(json|xml))$',
        TrackList.as_view(),
        name='track_list'),

    url(r'^librarys/(?P<pk>\d+)/tracks/create/$',
        TrackCreate.as_view(success_url="/musicapp/librarys"),
        name='track_create'),

    url(r'^librarys/(?P<pkr>\d+)/tracks/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        TrackDetail.as_view(),
        name='track_detail'),

    url(r'^librarys/(?P<pkr>\d+)/tracks/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Track,
            form_class=TrackForm),
        name='track_edit'),

    # RESTful API

    url(r'^api/auth/',
        include('rest_framework.urls', namespace='rest_framework')),

    url(r'^api/librarys/$',
        APILibraryList.as_view(), name='library-list'),
    url(r'^api/librarys/(?P<pk>\d+)/$',
        APILibraryDetail.as_view(), name='library-detail'),
    url(r'^api/libraryreviews/$',
        APILibraryReviewList.as_view(), name='libraryreview-list'),
    url(r'^api/libraryviews/(?P<pk>\d+)/$',
        APILibraryReviewDetail.as_view(), name='libraryreview-detail'),


    url(r'^api/artists/$',
        login_required(APIArtistList.as_view()), name='artist-list'),
    url(r'^api/artists/(?P<pk>\d+)/$',
        APIArtistDetail.as_view(), name='artist-detail'),

    url(r'^api/albums/$',
        login_required(APIAlbumList.as_view()), name='album-list'),
    url(r'^api/albums/(?P<pk>\d+)/$',
        APIAlbumDetail.as_view(), name='album-detail'),

    url(r'^api/tracks/$',
        login_required(APITrackList.as_view()), name='track-list'),
    url(r'^api/tracks/(?P<pk>\d+)/$',
        APITrackDetail.as_view(), name='track-detail'),

]
# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['api','json', 'xml'])

musicproject/musicproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.static import serve
from django.conf import settings

from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^musicapp/', include('musicapp.urls', namespace='musicapp')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })
    ]

musicproject/musicapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date

class Library(models.Model):
    name = models.TextField()
    genere = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('musicapp:library_detail', kwargs={'pk': self.pk})
    def averageRating(self):
        ratingSum = sum([float(review.rating) for review in self.libraryreview_set.all()])
        reviewCount = self.libraryreview_set.count()
        return ratingSum / reviewCount

class Artist(models.Model):
    nomArtista = models.TextField()
    tags = models.TextField(blank=True)
    image = models.ImageField(upload_to="Music_App", blank=True, null=True)
    web = models.URLField(blank=True)
    similars = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    Library =  models.ForeignKey(Library, null=True, related_name='artists')
    user = models.ForeignKey(User, null=True)

    def __unicode__(self):
        return u"%s" % self.nomArtista
    def get_absolute_url(self):
        return reverse('musicapp:artist_detail', kwargs={'pkr': self.Library.pk, 'pk': self.pk})

class Album(models.Model):
    nomAlbum = models.TextField()
    tag = models.TextField(blank=True)
    releasedate = models.TextField(blank=True)
    image = models.ImageField(upload_to="Music_App", blank=True, null=True)
    web = models.URLField(blank=True)
    artist = models.ForeignKey(Artist, blank=True, null=True)
    Library =  models.ForeignKey(Library, null=True, related_name='albums')
    user = models.ForeignKey(User, null=True)

    def __unicode__(self):
        return u"%s" % self.nomAlbum
    def get_absolute_url(self):
        return reverse('musicapp:album_detail', kwargs={'pkr': self.Library.pk, 'pk': self.pk})

class Track(models.Model):
    nomTrack = models.TextField()
    image = models.ImageField(upload_to="Music_App", blank=True, null=True)
    web = models.URLField(blank=True)
    duration = models.IntegerField(blank=True)
    playcount = models.IntegerField(blank=True)
    published = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    artist = models.ForeignKey(Artist, blank=True, null=True)
    album = models.ForeignKey(Album, blank=True, null=True)
    Library =  models.ForeignKey(Library, null=True, related_name='tracks')
    user = models.ForeignKey(User, null=True)

    def __unicode__(self):
        return u"%s" % self.nomTrack
    def get_absolute_url(self):
        return reverse('musicapp:track_detail', kwargs={'pkr': self.Library.pk, 'pk': self.pk})


class Review(models.Model):
    RATING_CHOICES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)

    class Meta:
        abstract = True

class LibraryReview(Review):
    library = models.ForeignKey(Library)

musicproject/musicapp/forms.py
from django.forms import ModelForm
from models import Library, Artist, Album, Track

class LibraryForm(ModelForm):
    class Meta:
        model = Library
        exclude = ('user', 'date',)

class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        exclude = ('user', 'date', 'library',)

class AlbumForm(ModelForm):
    class Meta:
        model = Album
        exclude = ('user', 'date', 'library',)

class TrackForm(ModelForm):
    class Meta:
        model = Track
        exclude = ('user', 'date', 'library',)

musicproject/musicapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import CreateView, UpdateView

from rest_framework import generics, permissions
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from models import Library, Artist, Album, Track, LibraryReview
from forms import LibraryForm, ArtistForm, AlbumForm, TrackForm
from serializers import LibrarySerializer, ArtistSerializer, AlbumSerializer, TrackSerializer,LibraryReviewSerializer

class ConnegResponseMixin(TemplateResponseMixin):

    def render_json_object_response(self, objects, **kwargs):
        json_data = serializers.serialize(u"json", objects, **kwargs)
        return HttpResponse(json_data, content_type=u"application/json")

    def render_xml_object_response(self, objects, **kwargs):
        xml_data = serializers.serialize(u"xml", objects, **kwargs)
        return HttpResponse(xml_data, content_type=u"application/xml")

    def render_to_response(self, context, **kwargs):
        if 'extension' in self.kwargs:
            try:
                objects = [self.object]
            except AttributeError:
                objects = self.object_list
            if self.kwargs['extension'] == 'json':
                return self.render_json_object_response(objects=objects)
            elif self.kwargs['extension'] == 'xml':
                return self.render_xml_object_response(objects=objects)
        return super(ConnegResponseMixin, self).render_to_response(context)

class LoginRequiredMixin(object):
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class CheckIsOwnerMixin(object):
    def get_object(self, *args, **kwargs):
        obj = super(CheckIsOwnerMixin, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user:
            raise PermissionDenied
        return obj

class LoginRequiredCheckIsOwnerUpdateView(LoginRequiredMixin, CheckIsOwnerMixin, UpdateView):
    template_name = 'musicapp/form.html'

class LibraryList(ListView, ConnegResponseMixin):
    model = Library
    queryset = Library.objects.filter(date__lte=timezone.now()).order_by('date')[:5]
    context_object_name = 'latest_library_list'
    template_name = 'musicapp/library_list.html'

class LibraryDetail(DetailView, ConnegResponseMixin):
    model = Library
    template_name = 'musicapp/library_detail.html'

    def get_context_data(self, **kwargs):
        context = super(LibraryDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = LibraryReview.RATING_CHOICES
        return context

class LibraryCreate(LoginRequiredMixin, CreateView):
    model = Library
    template_name = 'musicapp/form.html'
    form_class = LibraryForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(LibraryCreate, self).form_valid(form)

class ArtistList(ListView, ConnegResponseMixin):
    model = Artist
    queryset = Artist.objects.filter()
    context_object_name = 'latest_artist_list'
    template_name = 'musicapp/artist_list.html'

class ArtistCreate(LoginRequiredMixin, CreateView):
    model = Artist
    template_name = 'musicapp/form.html'
    form_class = ArtistForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.library = Library.objects.get(id=self.kwargs['pk'])
        return super(ArtistCreate, self).form_valid(form)

class ArtistDetail(DetailView, ConnegResponseMixin):
    model = Artist
    template_name = 'musicapp/artist_detail.html'


class AlbumList(ListView, ConnegResponseMixin):
    model = Album
    queryset = Album.objects.filter()
    context_object_name = 'latest_album_list'
    template_name = 'musicapp/album_list.html'

class AlbumCreate(LoginRequiredMixin, CreateView):
    model = Album
    template_name = 'musicapp/form.html'
    form_class = AlbumForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.library = Library.objects.get(id=self.kwargs['pk'])
        return super(AlbumCreate, self).form_valid(form)

class AlbumDetail(DetailView, ConnegResponseMixin):
    model = Album
    template_name = 'musicapp/album_detail.html'

class TrackList(ListView, ConnegResponseMixin):
    model = Track
    queryset = Track.objects.filter()
    context_object_name = 'latest_track_list'
    template_name = 'musicapp/track_list.html'

class TrackCreate(LoginRequiredMixin, CreateView):
    model = Track
    template_name = 'musicapp/form.html'
    form_class = TrackForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.library = Library.objects.get(id=self.kwargs['pk'])
        return super(TrackCreate, self).form_valid(form)

class TrackDetail(DetailView, ConnegResponseMixin):
    model = Track
    template_name = 'musicapp/track_detail.html'

@login_required()
### RESTful API views ###
def review(request, pk):
    library = get_object_or_404(Library, pk=pk)
    review = LibraryReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        library=library)
    review.save()
    return HttpResponseRedirect(reverse('musicapp:library_detail', args=(library.id,)))

class IsOwnerOrReadOnly(permissions.IsAuthenticatedOrReadOnly):

    def has_object_permission(self, request, view, obj):
        # Read permissions are allowed to any request,
        # so we'll always allow GET, HEAD or OPTIONS requests.
        if request.method in permissions.SAFE_METHODS:
            return True
        # Instance must have an attribute named `owner`.
        return obj.user == request.user

class APILibraryList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = Library
    queryset = Library.objects.all()
    serializer_class = LibrarySerializer

class APILibraryDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Library
    queryset = Library.objects.all()
    serializer_class = LibrarySerializer

class APILibraryReviewList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = LibraryReview
    queryset = LibraryReview.objects.all()
    serializer_class = LibraryReviewSerializer

class APILibraryReviewDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = LibraryReview
    serializer_class = LibraryReviewSerializer

class APIArtistList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = Artist
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer

class APIArtistDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Artist
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer

class APIAlbumList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = Album
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer

class APIAlbumDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Album
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer

class APITrackList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = Track
    queryset = Track.objects.all()
    serializer_class = TrackSerializer

class APITrackDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Track
    queryset = Track.objects.all()
    serializer_class = TrackSerializer

musicproject/musicapp/templates/musicapp/album_detail.html
{% extends "musicapp/base.html" %}

{% block content %}

<h1>
    {{ album.nomAlbum }}
    {% if user == album.user %}
        (<a href="{% url 'musicapp:album_edit' album.Library.id album.id %}">edit</a>)
    {% endif %}
</h1>

<p><b>tags:</b> {{ album.tag }}</p>
{% if album.image %}
    <p><img src="{{ album.image.url }}"/></p>
{% endif %}
<p><b>Releasedate:</b> {{ album.releasedate }}</p>
<p><b>Webpage:</b> {{ album.web }}</p>
<p><b>Artist:</b>{{ album.artist }}</p>
{% endblock %}

{% block footer %}
    Created by {{ album.user }}
{% endblock %}

musicproject/musicapp/templates/musicapp/artist_detail.html
{% extends "musicapp/base.html" %}

{% block content %}

<!--https://schema.org/MusicGroup (Can also be a solo musician) -->
<span vocab="http://schema.org/"  typeof="MusicGroup">


<h1>
      <span property="alternateName">{{ artist.nomArtista }}</span>
    {% if user == artist.user %}
        (<a href="{% url 'musicapp:artist_edit' artist.Library.id artist.id %}">edit</a>)
    {% endif %}
</h1>

<p><b>tags:</b>  <span property="genre">{{ artist.tags }}</span></p>
{% if artist.image %}
    <p><img src="{{ artist.image.url }}"/></p>
{% endif %}
<p><b>Webpage:</b>  <span property="url">{{ artist.web }}</span></p>
<p><b>Similar artists:</b> {{ artist.similars }}</p>
<p><b>Summary:</b>  {{ artist.summary }}</p>
{% endblock %}

{% block footer %}
    Created by {{ artist.user }}
{% endblock %}

musicproject/musicapp/templates/musicapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-2.2.3.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static "style/base.css" %}" />
    <title>{% block title %}MusicApp by MyRecommentdations.org{% endblock %}</title>
</head>

<body>

<div id="header">
    {% block header %}
        {% if user.username %}
            <p>User: {{ user.username }} | <a href="{% url 'logout' %}?next={{request.path}}">logout</a></p>
        {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">login</a></p>
        {% endif %}
    {% endblock %}
</div>

<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/musicapp/librarys">Home</a></li>
        </ul>
    {% endblock %}
</div>

<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>

<div id="footer">
    {% block footer %}{% endblock %}
</div>

</body>
</html>

musicproject/musicapp/templates/musicapp/form.html
{% extends "musicapp/base.html" %}
{% load staticfiles %}

{% block content %}

    <script>
        $(function() {
            $.getJSON("{% static "generes.json" %}", {}, function (generes) {
                $("#id_genere").autocomplete({
                    source: generes
                });
            });

            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                        $("#id_zipCode").val("");
                    }
                }
            });
        });
    </script>



    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>

{% endblock %}

musicproject/musicapp/templates/musicapp/library_detail.html
{% extends "musicapp/base.html" %}
{% block content %}


<!--https://schema.org/MusicPlaylist-->
<span vocab="http://schema.org/"  typeof="MusicPlaylist">

<h1>
    <span property="name">{{ library.name }}</span>
    {% if user == library.user %}
        (<a href="{% url 'musicapp:library_edit' library.id %}">edit</a>)
    {% endif %}
</h1>

<h2>
    <b>Artists</b>
    {% if user.is_authenticated %}
        (<a href="{% url 'musicapp:artist_create' library.id %}">add</a>)
    {% endif %}
</h2>
<ul>
    {% for artist in library.artists.all %}
        <li><a href="{% url 'musicapp:artist_detail' library.id artist.id  g%}">
            {{ artist.nomArtista }}</a></li>
    {% empty %}<li>Sorry, no artists for this library.</li>
    {% endfor %}
</ul>

<h2>
    <b>Albums</b>
    {% if user.is_authenticated %}
        (<a href="{% url 'musicapp:album_create' library.id %}">add</a>)
    {% endif %}
</h2>
<ul>
    {% for album in library.albums.all %}
        <li><a href="{% url 'musicapp:album_detail' library.id album.id  g%}">
            {{ album.nomAlbum }}</a></li>
    {% empty %}<li>Sorry, no albums for this library.</li>
    {% endfor %}
</ul>

<h2>
    <b>Tracks</b>
    {% if user.is_authenticated %}
        (<a href="{% url 'musicapp:track_create' library.id %}">add</a>)
    {% endif %}
</h2>
<ul>
    {% for track in library.tracks.all %}
        <li><a href="{% url 'musicapp:track_detail' library.id track.id  g%}">
            {{ track.nomTrack }}</a></li>
    {% empty %}<li>Sorry, no tracks for this library.</li>
    {% endfor %}
</ul>

<h2>Reviews</h2>
{% if library.libraryreview_set.all|length > 0 %}
<span rel="aggregateRating">
    <p typeof="AggregateRating">
        Average rating <span property="ratingValue">{{ library.averageRating|stringformat:".1f" }}</span>
        {% with library.libraryreview_set.all|length as reviewCount %}
        from <span property="reviewCount">{{ reviewCount }}</span> review{{ reviewCount|pluralize }}
        {% endwith %}
    </p>
</span>
<ul rel="review">
    {% for review in library.libraryreview_set.all %}
        <li typeof="Review">
            <p rel="reviewRating" typeof="Rating">
                <span property="worstRating" content="{{ RATING_CHOICES.0.0 }}"></span>
                <span property="ratingValue">{{ review.rating }}</span> star{{ review.rating|pluralize }}
                {% with RATING_CHOICES|last as best %}
                <span property="bestRating" content="{{ best.0 }}"></span>
                {% endwith %}
            </p>
            <p property="description">{{ review.comment }}</p>
            <p>Created by <span property="author">{{ review.user }}</span></p>
        </li>
    {% endfor %}
</ul>
</span>
{% endif %}

<h3>Add Review</h3>
<form action="{% url 'musicapp:review_create' library.id %}" method="post">
    {% csrf_token %}
    Message: <textarea name="comment" id="comment" rows="4"></textarea>
    <p>Rating:</p>
    <p>{% for rate in RATING_CHOICES %}
    <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.1 }}" />
    <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label>
    <br/>{% endfor %}
    </p>
    <input type="submit" value="Submit review" />
</form>

{% endblock %}
{% block footer %}
    Created by {{ library.user }} on {{ library.date }}
{% endblock %}

musicproject/musicapp/templates/musicapp/library_list.html
{% extends "musicapp/base.html" %}
{% block content %}
<h1>
    Music libraries:
    {% if user.is_authenticated %}(<a href="{% url 'musicapp:library_create' %}">add</a>){% endif %}
</h1>
<ul>
    {% for library in latest_library_list %}
        <li><a href="{% url 'musicapp:library_detail' library.id %}">
            {{ library.name }}</a></li>
    {% empty %}<li>Sorry, no music libraries registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}

musicproject/musicapp/templates/musicapp/track_detail.html
{% extends "musicapp/base.html" %}

{% block content %}

<h1>
    {{ track.nomTrack }}
    {% if user == track.user %}
        (<a href="{% url 'musicapp:track_edit' track.Library.id track.id %}">edit</a>)
    {% endif %}
</h1>
{% if track.image %}
    <p><img src="{{ track.image.url }}"/></p>
{% endif %}
<p><b>Webpage:</b>  {{ track.web }}</p>
<p><b>Duration:</b>  {{ track.duration }}s</p>
<p><b>Playcount:</b>  {{ track.playcount }}</p>
<p><b>Published:</b>  {{ track.published }}</p>
<p><b>Summary:</b>  {{ track.summary }}</p>
<p><b>Artist:</b>  {{ track.artist }}</p>
<p><b>Album:</b>  {{ track.album }}</p>
{% endblock %}

{% block footer %}
    Created by {{ track.user }}
{% endblock %}